spring.ai.chat.options.model: gpt-5.2
spring.devtools.restart.enabled: true

#Spring AI prompt completion logging logging for dev environment only
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true
spring.ai.chat.observations.log-completion=true


spring.ai.chat.observations.include-error-logging=true

#Helpful logs for debugging
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

logging.level.org.springframework.ai.chat.observation=DEBUG
logging.level.org.springframework.ai.chat.client.observation=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=testing-and-observability
